
name: Generate k8s yaml - Upload to Argo Repo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v4

    - name: Create dockerconfig.json secret
      run: |
        echo "${{ secrets.DOCKER_CONFIG_JSON }}" > dockerconfig.json

    - name: Use Node.js 22.1.0
      uses: actions/setup-node@v4
      with:
        node-version: 22.1.0
        cache: 'npm'
    - run: npm ci
    - run: npm  install -g cdk8s-cli
    - run: npm test -- -u
    - run: npm run build
    - run: |
        ls -a
    
    - name: upload cdk8s yaml
      uses: actions/upload-artifact@v4
      with:
        name: cdk8s-yaml
        path: dist/

  upload-cdk8s-yaml:

    needs: build
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    - name: Get latest commit subject
      run: |
        LATEST_COMMIT_SUBJECT=$(git log -1 --pretty=%s)
        echo "LATEST_COMMIT_SUBJECT=$LATEST_COMMIT_SUBJECT" >> $GITHUB_ENV

    - name: download cdk8s yaml artifact
      uses: actions/download-artifact@v4
      with:
        name: cdk8s-yaml
        path: k8s-yaml

    - name: Checkout target repository
      uses: actions/checkout@v4
      with:
        repository: 'dekaghub/cdk8s-issue-app-yaml'
        token: ${{ secrets.ARGO_YAML_REPO }}
        path: cdk8s-issue-app-yaml
    
    - name: copying cdk8s yaml
      run: cp -r k8s-yaml/* cdk8s-issue-app-yaml/app/

    - name: git push changes in argo repo
      run: |
        cd cdk8s-issue-app-yaml
        git config user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config user.name "dekaghub"
        git add .
        git commit -m "uploaded new YAML CI/CD - $LATEST_COMMIT_SUBJECT"
        git push
